version: '3.2'

services:
    mysql-server:
        container_name: mysqldb
        image: mysql/mysql-server
        ports:
            - "13306:3306"     
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: secret
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
    woocommerce:
        container_name: wordpress-woocommerce
        image: wordpress
        ports:
            - "20080:80"
        environment:
            WORDPRESS_DB_HOST: mysql-server:3306
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: secret
        depends_on:
            - mysql-server
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        environment:
            PMA_HOST: 'mysql-server'
            PMA_PORT: 3306
            PMA_USER: 'root'
            PMA_PASSWORD: "test"
        ports:
            - 8080:80
        depends_on:
            - mysql-server
