version: '3'

services:
    mysql-server:
        container_name: mysqldb
        image: mysql/mysql-server
        ports:
            - "13306:3306"     
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: secret
    woocommerce:
        container_name: wordpress-woocommerce
        image: wordpress
        ports:
            - "20080:80"
        environment:
            WORDPRESS_DB_HOST: mysql-server:3306
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: secret
        depends_on:
            - mysql-server
